spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.163.135:3306/test2?characterEncoding=utf8
    username: root
    password: 12345
    maxActive: 20 #最大活跃数
    initialSize: 5 #初始化数量
    maxWait: 60000 #最大连接等待超时时间
    poolPreparedStatements: true  #打开PSCache，并且指定每个连接PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto : update
server:
  port: 8400
